kind: pipeline
type: kubernetes
name: demo

clone:
  skip_verify: true

metadata:
  namespace: drone

# resource requests are defined on the pipeline level
resources:
  requests:
    cpu: 2000
    memory: 2000MiB

steps:
  - name: en
    image: alpine
    commands:
      - echo hello
    resources:
      # resource limits are defined for each step
      limits:
        cpu: 1000
        memory: 1000MiB

  - name: es
    image: alpine
    commands:
      - echo hola

  - name: fr
    image: alpine
    commands:
      - echo bonjour
