kind: pipeline
type: kubernetes
name: demo

clone:
  skip_verify: true

metadata:
  namespace: drone

# resource requests are defined on the pipeline level
resources:
  requests:
    cpu: 2000
    memory: 2000MiB

steps:
- name: greeting
  image: golang:1.12
  commands:
  - go build
  - go test
